--------------------------------------------------------------------
-- PLG German Localization (By Laurenz2016)
--------------------------------------------------------------------

PLG["deDE"] = {
	["msgs"] = {
		["ERR_LEARN"]     = "Gehe zu deinem Lehrer und Lerne das folgende Rezept:",
		["ERR_LEARNVEND"] = "Gehe zu dem unten stehenden Verkäufer und kaufe das folgende Rezept:",
		["ERR_LOW_LEVEL"] = "Du musst Level %s sein um das folgende Rezept zu erlernen:",
		["ERR_MAX_LEVEL"] = "Maximales Level erreicht, keine weiteren Rezepte verfügbar. PLG schliesst.",
		["ERR_MAX_SKILL"] = "Du hast das maximum deines Beruf levels erreicht. Gehe zu deinem Lehrer und lerne das nächste.",
		["ERR_DATA"]      = "Keine Daten gefunden. PLG schliesst.",
		["CREATE"]        = "Stelle %s von dem folgendem Rezept her, bis Beruflevel %s.",
		["TRAINER"]       = "Gehe zu deinem Lehrer!",
		["KEEP"]          = "Du musst diese behalten für spätere Rezepte.",
		["WAITING"]       = "Warte auf den Server...",
	},
	["labels"] = {
		["TITLE"]         = "Profession Leveling Guide",
		["NAME"]          = "PLG",
		["INSTRUCTIONS"]  = "Anleitung",
		["RECIPE"]        = "Rezept",
		["ALTERNATE"]     = "Alternative",
		["REAGENTS"]      = "Reagenzien",
		["QUEST"]         = "QUEST",
		["NPC"]           = "Verkäufer",
		["TRACKING"]      = "Verfolge fehlende Reagenzien",
		["CLRTRACKING"]   = "Zurücksetzen",	
		["HELPTITLE"]     = "PLG Hilfe",
	},	
	["tooltips"] = {
		["HELPTITLE"]     = "PLG Hilfe",
		["HELPTEXT"]      = "Klicke hier um die Hilfe anzuzeigen/verstecken",
		["DEBUGTITLE"]    = "PLG Debugging",
		["DEBUGTEXT"]     = "Anklicken um das Beruf-Leveling zu imitieren.",
		["TRACKING"]      = "Fehlende Reagenzien in dem Quest-Log anzeigen",	
		["CLRTRACKING"]   = "Reagenzien von dem Quest-Verfolgungs-Fenser entfernen",	
		["SELECT"]        = "(Anklicken zum anwählen)",
		["WAYPOINT"]      = "Anklicken um einen Wegpunkt zu setzen.",
		["QUEST1TITLE"]   = "Quest für das Rezept",
		["QUEST1"]        = "Dieses Rezept bekommst du mit der obenstehenden Questreihe.  Der Name des Questgebers und der Ort stehen dadrunter. ",
		["QUEST2TITLE"]   = "Vorausgesetzte Quest",
		["QUEST2"]        = "Diese Questreihe muss erst abgeschlossen werden. Der name des Questgebers und der Ort stehen dadrunter.",
		["VENDOR"]        = "Rezept Verkäufer",
		["VENDOR1"]       = "Dieses Rezept kannst du nur kaufen. Der Name des Verkäufers und der Ort stehen unterhalb. ",
		["NPC"]           = "NPC",
		["LOCATION"]      = "Standort",
	},
	["help"] = {	
		["TEXT"]          = "\n\n|cff000000Anleitung:|r\nDer Anleitungstext zeigt wichtige Informationen wie z.B. wieviel mal du was von welchem Rezept du herstellen sollst und wo du welche Rezepte her bekommst.  \n\n|cff000000RECIPES:|r\nPLG wechselt automatisch zu einem Rezept amhängig von deinem aktuellen Beruf-Level. Manichmal wird auch ein alternatives Rezept angezeigz.  Klicke es an um die Reagenzien für das Alternative Rezept anzuzeigen. Rezepte die nicht ausgewählt sind werden Grau angeziegt. Über jedem Rezept ist ein Farbbalken mit dem die bestimmte Schwierigkeit des Rezeptes angezeigt wird.  \n\n|cff000000REAGENTS:|r\nDer Guide zeigt dir die Gesammtanzahl von Zutaten an die du braucht um ein Beruf-Level abzuschließen. z.B. sollst du ein Elexier machen und braucht eine Phiole. Um zum nächsten Level zu kommen brauchst du 5 Elexiere der Guide sagt dir also das du 5 Phiolen besorgen sollst. \n\n|cff000000Verkäufer:|r\nManichmal kannst du ein Rezept nicht bei deinem Lehrer erlernen.  Ein Icon wird neben dem ausgewählen Rezept für den Verkäufer |T"..PLG.textures.VENDORRECIPE..":16|t oder die Questreihe |T"..PLG.textures.QUESTRECIPE..":16|t.  Der Tooltip dieses Icons zeigt den Namen der Quest an (wenn benötigt), oder Verkäufer und Standort.  Wenn du das Icon anklickst wird ein Wegpunkt mit TomTom oder Carbonite angezeigt der dich zu dem Verkäufer oder Questgeber führt. \n\n|cff000000OTHER NOTES:|r\n* Jeder gegenstand den man anklicken kann bringt den Mauszeiger zum leuchten wenn man drüberfährt. \n\n* Jedes Rezept, falls bekannt, wird automatisch im Beruffesnster ausgewählt.\n\n* Wenn du das maximale Level für einen Beruf erreicht hat wird das Fenster nicht mehr für diesen Beruf angezeigt.\n\n* 25 Punkte bevor du das maximum für deine momentane Berufsfertigkeit erreicht hast, warnt dich ein Orangener Text oben im Fenster das du deinen Lehrer besuchen solltest.\n\n|cff000000Viel Glück!",
		["Cooking"]       = "\n\n|cff000000Kochen:|r\nDer einfachste weg Kochen zu leveln wenn du noch unter level 85 bist, ist bei dem Pilgerfreudenfest mitzumachen.  Bei diesem Event kannst du ca von level 1-350 leveln und somit ein Großmeister werden.  Wenn du level 85 bist kannst du um Halbhügelmarkt in Pandaria gehen und mit Sungshin Eisentatz sprechen.  Dort kannst du kochen von 1-600 leveln. Wenn du kochen lernen möchtest wärend du spielst, wähle diesen Guide.",
		["Alchemy"]       = "\n\n|cff000000Alchemie:|r\nDieser Beruf ist am besten zusammen mit Kräuterkunde, du kannst viel Gold sparen wenn du diese beiden Berufe zusammen levelst weil du alle benötigten Kräuter farmen kannst.",
		["Blacksmithing"] = "\n\n|cff000000Schmiedekunst:|r\nDieser Beruf ist am besten zusammen mit Bergbau, du kannst viel Gold sparen wenn du diese beiden Berufe zusammen levelst weil du alle benötigten Metalle farmen kannst.",
		["Enchanting"] = "\n\n|cff000000Verzauberkunst:|r\nDieser Beruf ist am besten zusammen mit Schneiderei weil du die meisten Tücher/Kleider die du herstellst entzaubern kannst.",
		["Engineering"] = "\n\n|cff000000Ingenieurskunst:|r\nDieser Beruf ist am besten zusammen mit Bergbau, du kannst viel Gold sparen wenn du diese beiden Berufe zusammen levelst weil du alle benötigten Metalle farmen kannst.",
		["Inscription"] = "\n\n|cff000000Inschriftenkunde:|r\nDieser Beruf ist am besten zusammen mit Kräuterkunde, du kannst viel Gold sparen wenn du diese beiden Berufe zusammen levelst weil du alle benötigten Kräuter farmen kannst.",
		["Jewelcrafting"] = "\n\n|cff000000Juvelierskunst:|r\nDieser Beruf ist am besten zusammen mit Bergbau or Verzauberkunst, du kannst viel Gold sparen wenn du diese beiden Berufe zusammen levelst weil du alle benötigten Materialien farmen kannst, oder die hergestellten Sachen entzaubern kannst.",
		["Leatherworking"] = "\n\n|cff000000Lederverarbeitung:|r\nDieser Beruf ist am besten zusammen mit Kürschnerei, du kannst viel Gold sparen wenn du diese beiden Berufe zusammen levelst weil du alle benötigten Materialien farmen kannst.",
		["Tailoring"] = "\n\n|cff000000Schneiderei:|r\nDu wirst Tausende stoffe brauchen wenn du Schneiderei leveln möchtest. Es wird sehr viel Gold kosten wenn du diese ganzen Stoffe kaufen möchtest, oder wenn du sie farmen möchtest, dauert das auch sehr lange. Schneiderei ist am besten zusammen mit Verzauberkunst weil du die meisten Tücher/Kleider die du herstellst entzaubern kannst.",
	},
}